package com.xiaomiquan.greenDB;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xiaomiquan.entity.bean.UserLogin;
import com.xiaomiquan.entity.bean.kline.KLineBean;

import com.xiaomiquan.greenDB.UserLoginDao;
import com.xiaomiquan.greenDB.KLineBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userLoginDaoConfig;
    private final DaoConfig kLineBeanDaoConfig;

    private final UserLoginDao userLoginDao;
    private final KLineBeanDao kLineBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userLoginDaoConfig = daoConfigMap.get(UserLoginDao.class).clone();
        userLoginDaoConfig.initIdentityScope(type);

        kLineBeanDaoConfig = daoConfigMap.get(KLineBeanDao.class).clone();
        kLineBeanDaoConfig.initIdentityScope(type);

        userLoginDao = new UserLoginDao(userLoginDaoConfig, this);
        kLineBeanDao = new KLineBeanDao(kLineBeanDaoConfig, this);

        registerDao(UserLogin.class, userLoginDao);
        registerDao(KLineBean.class, kLineBeanDao);
    }
    
    public void clear() {
        userLoginDaoConfig.clearIdentityScope();
        kLineBeanDaoConfig.clearIdentityScope();
    }

    public UserLoginDao getUserLoginDao() {
        return userLoginDao;
    }

    public KLineBeanDao getKLineBeanDao() {
        return kLineBeanDao;
    }

}
